### ISSUE TITLE
.\objs\WM_W600.axf: error: L6050U: The code size of this image (242550 bytes) exceeds the maximum allowed for this version of the linker.

### ISSUE THREAD

**Issue by alxdhuang** [w600/sdk#2]
![image](https://user-images.githubusercontent.com/48013855/56257853-35adfd00-6100-11e9-83db-2898139ee946.png)

使用最新版的 demo 工程，build 失败了，是什么原因呢？

Keil 环境：
![image](https://user-images.githubusercontent.com/48013855/56258012-a5bc8300-6100-11e9-89c6-f7dfaada309b.png)

**Comment by thingsturn** [comment]
请查看 http://www.keil.com/support/docs/3755.htm
