### ISSUE TITLE
编译回显

### ISSUE THREAD

**Issue by muyongming** [w600/sdk#5]
编译回显一大堆增么办？

打开tools目录下的rules.mk，搜索 找到

> $(OBJODIR)/%.o:
在编译命令前加上@，整个编译世界清净了，希望默认修改一下吧，O.O

![image](https://user-images.githubusercontent.com/31030136/59577118-f34f6f00-90f4-11e9-90a6-c31caefa034b.png)

**Comment by thingsturn** [comment]
好的，感谢建议。 已修正此问题，[详情点此查看](https://github.com/w600/sdk/commit/1a1da08f9eb233d0d286142417ed9999568cf1a7#diff-94867a6425042460f36d181256e55f05)
